// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma CLI (migrate/studio) talks to Postgres directly rather than
  // through Neon's pooled connection, since DDL over a pooler is unreliable.
  // The running app uses DATABASE_URL (pooled) via src/lib/prisma.ts instead.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
